---
layout: post
title: "20. Excepciones c++" 
date: 2028-08-04 21:07:00 
categories: coding
---
<b>Capturando excepciones</b><br>
Las excepciones son un mecanismo de c++ para capturar errores que se producen
en tiempo de ejecucion. Un programa puede estar bien hecho pero por causas exogenas
pueden producirse errores. <br>
Mediante este sistema hacemos que el codigo sea mucho mas ROBUSTO.
<pre>
/**
* Excepciones.cpp
* codigo que muestra como capturar excepciones y evitar que el programa
* finalice inesperadamente.
*
* Pello Xabier Altadill Izura
*
*/

#include &lt;iostream.h&gt;
#include &lt;fstream.h&gt;
#include &lt;stdexcept.h&gt; 

// programa principal, para las pruebas
int main () {
int i;
float flotante;
char *palabra;
char buffer[5];
ifstream ficheroInexistente;

// para capturar excepciones debemos crear un bloque try-catch
// que englobe algun momento problematico o critico del programa:
// try { codigo; } catch(TipoDeError)  { codigo_corrector; }

// lo habitual suele ser alguna situacion que dependa de la existencia
// o no de un fichero, la entrada de datos de un usuario, etc..
// El programa no puede controlar lo que le meten, pero puede estar
// preparado para el error, reconducir la ejecucion y corregir la situacion

try 
{ // inicio del bloque. Preparamos una serie de putadas...
cout &lt;&lt; "Mete lo primero que se te ocurra, distinto de float: " &lt;&lt; endl;
cin &gt;&gt; flotante;

char * buff = new char[100000000];
ficheroInexistente.open("MotorDeAgua.txt");
ficheroInexistente.getline(buffer,255);
ficheroInexistente.close();
 }
 catch(std::bad_alloc& error_memoria)
 {
    cout &lt;&lt; "Error de asignacion"  &lt;&lt; error_memoria.what() &lt;&lt; endl; 
    //... handle exception thrown by operator new
 } // podemos seguir capturando
catch (std::exception& stdexc) 
{ // este es el tipo de error que se espera
  // y entre llaves metemos el codigo que se ejecuta en caso de error.
    cout &lt;&lt; "Error general, mensaje: " &lt;&lt; stdexc.what() &lt;&lt; endl;
}

cin &gt;&gt; i;
return 1;
}
</pre>
<b>Excepciones personalizadas</b><br>
Una clase puede definir sus propias excepciones. Un mecanismo muy util
para malos usos de los objetos. 
<br>Definimos la clase coche y preparamos el codigo para capturar posibles
fallos debidos a la falta de combustible.
<pre>
/**
* Coche.hpp
* Definicion de la clase coche, en la que se muestra el uso de excepciones
*
* Pello Xabier Altadill Izura 
* 
*/

#include&lt;iostream.h&gt;

class Coche {
public:
	Coche();
	Coche(char *m,int cil,int cab, int litros);
	~Coche();
	
	void arranca();
	void echaCombustible();
	void detiene();
	void acelera();
	
private:
	char *marca;
	int cilindrada;
	int caballos; 
	int litrosCombustible;

};

// clase exclusiva para excepciones.
// Nota: la podemos definir DENTRO de la Clase coche, como un atributo MAS
class Averia {
    public:
        // constructor
        Averia():mensaje("Error") {
        }
        // constructor con mensaje
        Averia(char *mensaje) {
                this->mensaje = mensaje;
        }
        
        char* dimeQuePasa() { return this->mensaje; };
    private:
        char *mensaje;
};
</pre>
Y la implementacion
<pre>
/**
* Coche.cpp
* Implementacion de la clase coche, en la que se muestra el uso de excepciones
*
* Pello Xabier Altadill Izura 
* Compilacion: g++ -o Coche Coche.cpp
*/

#include "Coche.hpp"


Coche::Coche() {
 cout &lt;&lt; "Coche creado." &lt;&lt; endl;
}

Coche::Coche (char *m,int cil,int cab, int litros) {
  marca = m;
  cilindrada = cil;
  caballos = cab;
  litrosCombustible = litros;
 cout &lt;&lt; "Coche creado." &lt;&lt; endl;
}

Coche::~Coche() {
 cout &lt;&lt; "Coche destruido." &lt;&lt; endl;
}

// el coche arranca
void Coche::arranca() {
    // si no hay combustible: EXCEPCION!
    if (litrosCombustible == 0) {
        throw Averia();      
    }
    litrosCombustible--;
 cout &lt;&lt; "Arrancando: brummm! " &lt;&lt; endl;
}

// el coche se detien
void Coche::detiene() {
 cout &lt;&lt; "Deteniendo coche " &lt;&lt; endl;
}

// el coche acelera
void Coche::acelera() {
    if (litrosCombustible == 0) {
        throw Averia("No puedo acelerar sin combustible");      
    }
 cout &lt;&lt; "Acelerando: BRRRRRUMMMMmmmmmmmmh!! " &lt;&lt; endl;
}

// funcion principal para pruebas
int main () {
int i;
Coche buga("Seat",250,1300,0);
Coche tequi("Audi",260,1500,1);

// vamos a arrancar el coche pero si algo falla
// capturamos la excepcion
try {
buga.arranca();
} catch (Averia excepcion) {
    cout &lt;&lt; "Excepcion. Jar que no puedo. " &lt;&lt; endl;
}

// arracamos el tequi
tequi.arranca();

// provocamos la excepcion y la capturamos mostrando la explicacion.
try {
buga.acelera();
} catch (Averia excepcion) {
    cout &lt;&lt; "Jar que no puedo. " &lt;&lt; excepcion.dimeQuePasa() &lt;&lt; endl;
}

cin &gt;&gt; i;
return 0;
}
</pre>
